apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: eventcatalog

build:
  local:
    push: true
    tryImportMissing: true
  tagPolicy:
    inputDigest: {}
  insecureRegistries:
    - ${REGISTRY_CLUSTER}
  artifacts:
    - image: eventcatalog
      context: .
      custom:
        buildCommand: just build-push-image
        dependencies:
          paths:
            - eventcatalog/Dockerfile
            - asyncapi/
