server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    absolute_redirect off;

    location /observability/eventcatalog {
        try_files $uri /observability/eventcatalog/index.html;
    }

    # Health check
    location /health {
        return 200 "ok";
        add_header Content-Type text/plain;
    }
}
